spring:
  application:
    name: Cointoss


  datasource:
    url: jdbc:postgresql://localhost:5432/cointoss
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    baseline-on-migrate: true


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
