spring:
  application:
    name: Cointoss


  datasource:
    url: jdbc:postgresql://localhost:5432/cointoss
    username: myappuser
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 900 # 15 minutes
    RefreshTokenExpiration: 604800 # 7 days
